### ISSUE TITLE
url demo or screenshot

### ISSUE THREAD

**Issue by johnfelipe** [hias234/AustrianParliamentAnalyzer#1]

**Comment by hias234** [comment]
can you please give a more precise description of your request?

**Comment by johnfelipe** [comment]
Can you give me url demo or screenshots for view functionality

**Comment by hias234** [comment]
The project is in a early stage - there is no such thing as a UI yet. Until now, the only funcitonality is the extraction of data from the website of the Austrian parliament and saving the data into a DB.
